/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f9',
        'surface-dim': '#dbdad9',
        'surface-bright': '#fbf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#484457',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        outline: '#797489',
        'outline-variant': '#c9c3da',
        'surface-tint': '#6028ff',
        primary: '#4800d6',
        'on-primary': '#ffffff',
        'primary-container': '#6028ff',
        'on-primary-container': '#dcd3ff',
        'inverse-primary': '#cabeff',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e2e2',
        'on-secondary-container': '#646464',
        tertiary: '#454747',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5d5e5e',
        'on-tertiary-container': '#d8d8d8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e6deff',
        'primary-fixed-dim': '#cabeff',
        'on-primary-fixed': '#1c0062',
        'on-primary-fixed-variant': '#4800d6',
        'secondary-fixed': '#e2e2e2',
        'secondary-fixed-dim': '#c6c6c6',
        'on-secondary-fixed': '#1b1b1b',
        'on-secondary-fixed-variant': '#474747',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        background: '#fbf9f9',
        'on-background': '#1b1c1c',
        'surface-variant': '#e3e2e2',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        'body-lg': ['Space Grotesk'],
        'display-xl': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
        'label-mono': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'body-md': ['Space Grotesk'],
      },
      spacing: {
        gutter: '16px',
        unit: '4px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
