export const ROUTES = {
  HOME: "/",
  SHOP: "/shop",
  PRODUCT: "/product",
  CART: "/cart",
  CHECKOUT: "/checkout",
  PAYMENT: "/payment",
  SUCCESS: "/success",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  WISHLIST: "/wishlist",
  PROFILE: "/profile",
  ORDERS: "/orders",
  ADDRESSES: "/addresses",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  UNAUTHORIZED: "/unauthorized",
  CATEGORIES: "/categories",
  SEARCH: "/search",
};
